### ISSUE TITLE
[KotH/5v5] Highrise

### ISSUE THREAD

**Issue by Blazy-36** [OvercastCommunity/scrimmage-maps#54]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) to this map
- [X] I have provided an XML file
- [X] I have uploaded the map zip file to a file sharing service

# Map Name
Highrise

## Gamemode & Map Description  
5v5 Koth
City rooftop theme

## Map Image
![2022-04-12_18 19 45](https://user-images.githubusercontent.com/56277290/163071446-760e5565-d503-426b-93ec-590dcc1f750d.png)
![2022-04-12_18 20 12](https://user-images.githubusercontent.com/56277290/163071450-e695b577-2596-4722-b31f-e5e588a28705.png)

## Download Link
(https://drive.google.com/drive/folders/12O34hdyJO8hu7sXzorXPOX-5DzvVxJMj?usp=sharing)

**Comment by lefckntea** [comment]
hope this wins <3
