### ISSUE TITLE
[KoTF/5v5] Sunstroke

### ISSUE THREAD

**Issue by lefckntea** [OvercastCommunity/scrimmage-maps#58]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) to this map
- [x] I have provided an XML file
- [x] I have uploaded the map zip file to a file sharing service

# Map Name
Sunstroke KoTF

## Gamemode & Map Description  
Sunstroke KoTF

## Screenshots
Sunstroke KoTF

## Download Link
Sunstroke KoTF
https://www.dropbox.com/s/i75fc3p0y4ls4ix/Sunstroke_KoTF.zip?dl=0
![map](https://user-images.githubusercontent.com/39029307/163283600-4f69b543-7611-4bcd-ac3e-44a286419dec.png)

**Comment by calcastor** [comment]
thanks for the submission but we are not accepting or testing troll submissions. however, it has been loaded anyway in case anyone wants to take a look 👍

**Comment by lefckntea** [comment]
its a real map its probably better than other maps
